micronaut:
  application:
    name: store
  server:
    port: 8080

datasources:
  default:
    url: jdbc:postgresql://localhost:5432/product
    driverClassName: org.postgresql.Driver
    username: product
    password: 'product-mcrnt'
    auto-commit: true

liquibase:
  datasources:
    default:
      change-log: 'classpath:db/liquibase-changelog.xml'

eureka:
  client:
    registration:
      enabled: true
    defaultZone: ${EUREKA_HOST:localhost}:${EUREKA_PORT:8762}

rabbitmq:
  uri: amqp://localhost:5672